# ================================ Ollama ================================

from ollama/ollama:latest AS ollama

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ollama.sh /app/ollama.sh

RUN chmod +x /app/ollama.sh

ENTRYPOINT [ "./ollama.sh" ]
