llm:
  model: "mistral:latest"
  temperature: 0

embeddings:
  class: "E5MpsEmbedder"
  model_name: "intfloat/e5-small-v2"
  batch_size: 16

vector_store:
  type: "faiss"
  index_dir: "rag/FAISS_vectorstore"

data:
  bibtex_url: "https://eceb.astro.uni-bonn.de/public/Euclid.bib"
  arxiv_pdf_base_url: "https://arxiv.org/pdf/"
  chunk_size: 800
  chunk_overlap: 100

deduplication:
  similarity_threshold: 0.97
  rerank_threshold: 0.85
  reranker_model: "cross-encoder/stsb-roberta-base"
  k_candidates: 5
  max_embedding_logs: 3
  debug_mode: true
