llm:
  model: "gemma3:4b"
  temperature: 0

embeddings:
  class: "E5MpsEmbedder"
  model_name: "intfloat/e5-small-v2"
  batch_size: 16

vector_store:
  type: "faiss"
  index_dir: "rag/FAISS_vectorstore"

data:
  bibex_path: "https://eceb.astro.uni-bonn.de/public/Euclid.bib"
  chunk_size: 800
  chunk_overlap: 100
