llm:
  # Available models at https://ollama.com/library
  model: "granite3.2:latest"
  temperature: 0
  base_url: "http://ollama:11434"


embeddings:
  class: "E5MpsEmbedder"
  model_name: "intfloat/e5-small-v2"
  batch_size: 16

vector_store:
  type: "faiss"
  redmine_index_dir: "redmine_vector_store"
  public_data_index_dir: "public_data_vector_store"

json_data:
  redmine_json_dir: "/home/gimener/Documents/Euclid/checkOps/check_redmine/tmp/sys/"
  chunk_size: 800
  deduplication_key_fields:
    - "project_id"
    - "page_name"
    - "updated_on"
  json_root_key: pages

pdf_data:
  bibtex_url: "https://eceb.astro.uni-bonn.de/public/Euclid.bib"
  arxiv_pdf_base_url: "https://arxiv.org/pdf/"
  chunk_size: 800
  chunk_overlap: 100

dpdd_data:
  config: "python/euclid/rag/ingestion/config/ingest_dpdd_config.yaml"

deduplication:
  similarity_threshold: 0.97
  rerank_threshold: 0.85
  reranker_model: "cross-encoder/stsb-roberta-base"
  k_candidates: 5
  max_embedding_logs: 3
  debug_mode: true
